Feature friendship v1
mikethreels/ror-social-scaffold pull request #2
Opened 2020-07-24 22:42 UTC by mikethreels

## milestone 2: Friendship v1

### in this milestone we:
- [x] implemented friendship associations.
- [x] added invite, accept and ignore buttons.
- [x] filtered the timeline posts on friends and user posts.

2020-07-25 00:39 UTC, maelfosso requested changes
# Changes required :red_circle

Hello,

Thank you for the effort put into this milestone.
To move forward there are some changes to apply

1. After sign up, I got this error
![Screenshot at 2020-07-24 23:55:12](https://user-images.githubusercontent.com/8848104/88444943-93f38080-ce17-11ea-8d2e-06741a03bf76.png)


2. Instead of using the `UsersController` for handling friendship request. I suggest you to create `Friendship` controllers and use the `create`, `delete` and `update` actions for everything related to friendship request

3. Write integrations tests.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-25 00:39 UTC, maelfosso commented on app/views/users/show.html.erb
> +  <% end %>
We called that logic into views.
Please, use **views helpers** to handle that.

Don't forget to handle it in other views like `index.html.erb`

2020-07-25 00:39 UTC, maelfosso commented on app/controllers/application_controller.rb
> +  end
It seems like there is a problem here

2020-07-28 15:29 UTC, santiagorodriguezbermudez commented
## Code review # 1

### On this code review we accomplished:
- [x] We created the friendship controller and helper methods
- [x] Move the logic from views into the helper methods
- [x] Implemented integration and unit tests

2020-07-28 17:52 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a brilliant job with this project. :clap:
#### You can go ahead and merge !!!

2020-07-28 19:04 UTC, merged